; configurar as chaves de acesso ao banco de dados
[database]
db_driver   = pgsql
db_host     = 127.0.0.1
db_port     = 5432
db_name     = biblioteca_escola
db_user     = postgres
db_pass     = postgres
